// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Handlers;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(FactorySystemsDbContext))]
    [Migration("20251020233857_MigrationEnum")]
    partial class MigrationEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("WebApi.Models.SystemsDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CostCenter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailSupport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemsDbSet");

                    b.HasData(
                        new
                        {
                            Id = new Guid("57f33d84-5f82-4449-b486-151d39c9a280"),
                            ApplicationCode = "123ABC",
                            ApplicationName = "CustomerSystem",
                            CostCenter = "ABC112",
                            Database = "SQLServer",
                            EmailSupport = "[\"customer1@company.com\",\"customer2@company.com\"]",
                            InstallationLocation = "Main Server",
                            Status = "Ativo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
